// Generated by scripts/gen-champion-lanes.mjs — do not edit by hand.
//
// Which lanes each champion is actually played in, most common first, derived
// from Oracle's Elixir pro match data. Riot's champion tags are classes and
// cannot answer this: Gragas is a Fighter in all three of his lanes.
//
// Several lanes are kept where a champion genuinely flexes, so the draft can
// offer a choice rather than assert a wrong one.
import { Role } from '../models/team.models';

export const CHAMPION_LANES: Readonly<Record<string, readonly Role[]>> = {
  "Aatrox": [
    "Top",
    "Jungle"
  ],
  "Ahri": [
    "Mid"
  ],
  "Akali": [
    "Mid"
  ],
  "Akshan": [
    "Top",
    "Mid"
  ],
  "Alistar": [
    "Support"
  ],
  "Ambessa": [
    "Top",
    "Jungle"
  ],
  "Amumu": [
    "Support",
    "Jungle"
  ],
  "Anivia": [
    "Mid",
    "Top",
    "Support"
  ],
  "Annie": [
    "Mid"
  ],
  "Aphelios": [
    "ADC"
  ],
  "Ashe": [
    "ADC"
  ],
  "Aurelion Sol": [
    "Mid"
  ],
  "Aurora": [
    "Mid",
    "Top"
  ],
  "Azir": [
    "Mid"
  ],
  "Bard": [
    "Support"
  ],
  "Bel'Veth": [
    "Jungle"
  ],
  "Blitzcrank": [
    "Support"
  ],
  "Brand": [
    "ADC",
    "Jungle",
    "Mid",
    "Top"
  ],
  "Braum": [
    "Support"
  ],
  "Briar": [
    "Jungle"
  ],
  "Caitlyn": [
    "ADC"
  ],
  "Camille": [
    "Support",
    "Top"
  ],
  "Cassiopeia": [
    "Mid"
  ],
  "Cho'Gath": [
    "Top",
    "Jungle"
  ],
  "Corki": [
    "ADC"
  ],
  "Darius": [
    "Top",
    "Jungle"
  ],
  "Diana": [
    "Jungle",
    "Mid"
  ],
  "Dr. Mundo": [
    "Jungle",
    "Top"
  ],
  "Draven": [
    "ADC"
  ],
  "Ekko": [
    "Mid"
  ],
  "Elise": [
    "Support"
  ],
  "Ezreal": [
    "ADC"
  ],
  "Fiddlesticks": [
    "Jungle",
    "Support"
  ],
  "Fiora": [
    "Top"
  ],
  "Fizz": [
    "Mid",
    "Jungle"
  ],
  "Galio": [
    "Mid",
    "Top"
  ],
  "Gangplank": [
    "Top"
  ],
  "Garen": [
    "Top"
  ],
  "Gnar": [
    "Top"
  ],
  "Gragas": [
    "Top"
  ],
  "Graves": [
    "Jungle"
  ],
  "Gwen": [
    "Top"
  ],
  "Hecarim": [
    "Jungle"
  ],
  "Heimerdinger": [
    "ADC",
    "Support",
    "Top"
  ],
  "Hwei": [
    "Mid"
  ],
  "Illaoi": [
    "Top"
  ],
  "Irelia": [
    "Top",
    "Mid"
  ],
  "Ivern": [
    "Jungle"
  ],
  "Janna": [
    "Support"
  ],
  "Jarvan IV": [
    "Jungle"
  ],
  "Jax": [
    "Top",
    "Jungle"
  ],
  "Jayce": [
    "Top",
    "Jungle"
  ],
  "Jhin": [
    "ADC"
  ],
  "Jinx": [
    "ADC"
  ],
  "K'Sante": [
    "Top"
  ],
  "Kai'Sa": [
    "ADC"
  ],
  "Kalista": [
    "ADC"
  ],
  "Karma": [
    "Support"
  ],
  "Karthus": [
    "Jungle",
    "Mid",
    "ADC"
  ],
  "Kassadin": [
    "Mid",
    "Top"
  ],
  "Katarina": [
    "Mid"
  ],
  "Kayle": [
    "Top"
  ],
  "Kayn": [
    "Jungle",
    "Top"
  ],
  "Kennen": [
    "Top"
  ],
  "Kha'Zix": [
    "Jungle"
  ],
  "Kindred": [
    "Jungle"
  ],
  "Kled": [
    "Top"
  ],
  "Kog'Maw": [
    "ADC",
    "Mid"
  ],
  "LeBlanc": [
    "Mid"
  ],
  "Lee Sin": [
    "Jungle"
  ],
  "Leona": [
    "Support"
  ],
  "Lillia": [
    "Jungle"
  ],
  "Lissandra": [
    "Mid"
  ],
  "Locke": [
    "Mid"
  ],
  "Lucian": [
    "ADC"
  ],
  "Lulu": [
    "Support"
  ],
  "Lux": [
    "Support",
    "Mid"
  ],
  "Malphite": [
    "Top",
    "Jungle"
  ],
  "Malzahar": [
    "Mid"
  ],
  "Maokai": [
    "Jungle",
    "Support"
  ],
  "Master Yi": [
    "Jungle"
  ],
  "Mel": [
    "Mid",
    "ADC"
  ],
  "Milio": [
    "Support"
  ],
  "Miss Fortune": [
    "ADC"
  ],
  "Mordekaiser": [
    "Top"
  ],
  "Morgana": [
    "Mid",
    "Support",
    "Jungle"
  ],
  "Naafiri": [
    "Jungle"
  ],
  "Nami": [
    "Support"
  ],
  "Nasus": [
    "Jungle",
    "Top"
  ],
  "Nautilus": [
    "Support"
  ],
  "Neeko": [
    "Support"
  ],
  "Nidalee": [
    "Jungle",
    "Top"
  ],
  "Nilah": [
    "ADC"
  ],
  "Nocturne": [
    "Jungle"
  ],
  "Nunu & Willump": [
    "Jungle"
  ],
  "Olaf": [
    "Top",
    "Jungle"
  ],
  "Orianna": [
    "Mid"
  ],
  "Ornn": [
    "Top"
  ],
  "Pantheon": [
    "Jungle"
  ],
  "Poppy": [
    "Support",
    "Jungle",
    "Top"
  ],
  "Pyke": [
    "Support"
  ],
  "Qiyana": [
    "Jungle"
  ],
  "Quinn": [
    "Top",
    "Mid"
  ],
  "Rakan": [
    "Support"
  ],
  "Rammus": [
    "Jungle",
    "Support"
  ],
  "Rek'Sai": [
    "Top",
    "Jungle"
  ],
  "Rell": [
    "Support"
  ],
  "Renata Glasc": [
    "Support"
  ],
  "Renekton": [
    "Top"
  ],
  "Rengar": [
    "Jungle"
  ],
  "Riven": [
    "Top"
  ],
  "Rumble": [
    "Top"
  ],
  "Ryze": [
    "Mid"
  ],
  "Samira": [
    "ADC"
  ],
  "Sejuani": [
    "Jungle"
  ],
  "Senna": [
    "ADC",
    "Support"
  ],
  "Seraphine": [
    "Support"
  ],
  "Sett": [
    "Top",
    "Support"
  ],
  "Shaco": [
    "Jungle",
    "Support"
  ],
  "Shen": [
    "Support",
    "Top"
  ],
  "Shyvana": [
    "Jungle",
    "Top"
  ],
  "Singed": [
    "Top"
  ],
  "Sion": [
    "Top"
  ],
  "Sivir": [
    "ADC"
  ],
  "Skarner": [
    "Jungle"
  ],
  "Smolder": [
    "ADC",
    "Mid"
  ],
  "Sona": [
    "Support"
  ],
  "Soraka": [
    "Support"
  ],
  "Swain": [
    "Mid",
    "Top"
  ],
  "Sylas": [
    "Mid",
    "Jungle"
  ],
  "Syndra": [
    "Mid",
    "ADC"
  ],
  "Tahm Kench": [
    "Support",
    "ADC"
  ],
  "Taliyah": [
    "Mid"
  ],
  "Talon": [
    "Jungle"
  ],
  "Taric": [
    "Support"
  ],
  "Teemo": [
    "Top"
  ],
  "Thresh": [
    "Support"
  ],
  "Tristana": [
    "ADC",
    "Mid",
    "Top"
  ],
  "Trundle": [
    "Jungle"
  ],
  "Tryndamere": [
    "Top",
    "Jungle"
  ],
  "Twisted Fate": [
    "Mid",
    "Top"
  ],
  "Twitch": [
    "ADC"
  ],
  "Udyr": [
    "Top",
    "Jungle"
  ],
  "Urgot": [
    "Top",
    "Jungle"
  ],
  "Varus": [
    "ADC",
    "Top"
  ],
  "Vayne": [
    "Top",
    "ADC"
  ],
  "Veigar": [
    "Mid",
    "ADC"
  ],
  "Vel'Koz": [
    "Mid",
    "ADC",
    "Support"
  ],
  "Vex": [
    "Mid",
    "Top"
  ],
  "Vi": [
    "Jungle"
  ],
  "Viego": [
    "Jungle"
  ],
  "Viktor": [
    "Mid",
    "ADC"
  ],
  "Vladimir": [
    "Mid",
    "Top",
    "ADC"
  ],
  "Volibear": [
    "Top",
    "Jungle"
  ],
  "Warwick": [
    "Top",
    "Jungle"
  ],
  "Wukong": [
    "Jungle"
  ],
  "Xayah": [
    "ADC"
  ],
  "Xerath": [
    "Mid",
    "ADC"
  ],
  "Xin Zhao": [
    "Jungle"
  ],
  "Yasuo": [
    "Mid",
    "Top",
    "ADC"
  ],
  "Yone": [
    "Mid",
    "Top"
  ],
  "Yorick": [
    "Top"
  ],
  "Yunara": [
    "ADC"
  ],
  "Yuumi": [
    "Support"
  ],
  "Zaahen": [
    "Top",
    "Jungle"
  ],
  "Zac": [
    "Jungle",
    "Top",
    "Support"
  ],
  "Zed": [
    "Mid",
    "Jungle"
  ],
  "Zeri": [
    "ADC"
  ],
  "Ziggs": [
    "ADC",
    "Mid"
  ],
  "Zilean": [
    "Support",
    "Top",
    "Mid"
  ],
  "Zoe": [
    "Mid"
  ],
  "Zyra": [
    "Jungle",
    "Support"
  ]
};
